name = "company-website"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".worker-next"

[[d1_databases]]
binding = "DB"
database_name = "farmkung-db"
database_id = "1dbc5d46-3915-41bb-a0c8-7ddb6950b851"

[[r2_buckets]]
binding = "R2_STORAGE"
bucket_name = "farmkung-assets"
